pipeline {
  agent {
    docker { image 'bitnami/dotnet-sdk:latest' }
  }
  stages {
    stage('Verify') {
      steps {
        sh '''
          dotnet --list-sdks
          dotnet --list-runtimes
        '''
        sh 'printenv'
      }
    }
  }
}
