pipeline {
  agent any
  parameters {
    booleanParam(name: 'RC', defaultValue: false, description: 'Is this a Release Candidate?')
  }
  environment {
    VERSION = "0.1.0"
    VERSION_RC = "rc.2"
  }
  stages {
    stage('Audit tools') {
      steps {
        auditTools()
      }
    }
    stage('Build') {
      environment {
        VERSION_SUFFIX = getVersionSuffic()
      }
      steps {
        echo "Building version: ${VERSION} with suffix: ${VERSION_SUFFIX}"
      }
    }
    stages('Public') {
      steps {
        sh 'cat /etc/os-release > public.txt'
      }
    }
  }
  post {
    success {
      archiveArtifacts artifacts: 'public.txt'
    }
  }
}

String getVersionSuffic() {
  if (params.RC) {
    return env.VERSION_RC
  } else {
    return env.VERSION_RC + '+ci.' + env.BUILD_NUMBER
  }
}

void auditTools() {
  sh '''
    git version
  '''
}
