library identifier: 'jenkins-pipeline-library@main',
        retriever: modernSCM([$class: 'GitSCMSource',
        remote: 'https://github.com/cckcoder/jenkins-pipeline-library.git'])

pipeline {
  agent any
  stages {
    stage('Audit Tools') {
      steps {
        auditTools()
      }
    }
  }
}
