pipeline {
  agent any
  environment {
    RELEASE='20.04'
  }
  stages {
    stage('Build') {
      environment {
        LOG_LEVEL='INFO'
      }
      parallel {
        stage('linux-arm64') {
          steps {
            echo "Building release ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}"
          }
        }
        stage('windows') {
          steps {
            echo "Building release ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}"
          }
        }
        stage('OSX') {
          steps {
            echo "Building release ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}"
          }
        }
      }
    }
    stage('Test') {
      steps {
        echo "Testing release ${RELEASE}"
      }
    }
    stage('Deploy') {
      input {
        message 'Deploy?'
        ok 'Do it!'
        parameters {
          string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
        }
      }
      steps {
        echo "Deploy release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
      }
    }
  }
  post {
    always {
      echo 'Prints whether deploy happened or not, success or failure'
    }
  }
}
